// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: api_tokens.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, label, token_hash)
VALUES (
    (SELECT id FROM users WHERE users.uuid = $1),
    $2,
    $3
)
RETURNING id, uuid, user_id, label, token_hash, last_used_at, created_at, updated_at
`

type CreateAPITokenParams struct {
	UserUuid  uuid.UUID `db:"user_uuid" json:"user_uuid"`
	Label     string    `db:"label" json:"label"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken, arg.UserUuid, arg.Label, arg.TokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Label,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens
WHERE api_tokens.uuid = $1
  AND user_id = (SELECT id FROM users WHERE users.uuid = $2)
`

type DeleteAPITokenParams struct {
	TokenUuid uuid.UUID `db:"token_uuid" json:"token_uuid"`
	UserUuid  uuid.UUID `db:"user_uuid" json:"user_uuid"`
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIToken, arg.TokenUuid, arg.UserUuid)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT t.id, t.uuid, t.user_id, t.label, t.token_hash, t.last_used_at, t.created_at, t.updated_at,
       u.uuid AS user_uuid
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
`

type GetAPITokenByHashRow struct {
	ID         int32        `db:"id" json:"id"`
	Uuid       uuid.UUID    `db:"uuid" json:"uuid"`
	UserID     int32        `db:"user_id" json:"user_id"`
	Label      string       `db:"label" json:"label"`
	TokenHash  string       `db:"token_hash" json:"token_hash"`
	LastUsedAt sql.NullTime `db:"last_used_at" json:"last_used_at"`
	CreatedAt  time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time    `db:"updated_at" json:"updated_at"`
	UserUuid   uuid.UUID    `db:"user_uuid" json:"user_uuid"`
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Label,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, uuid, user_id, label, token_hash, last_used_at, created_at, updated_at FROM api_tokens
WHERE user_id = (SELECT id FROM users WHERE users.uuid = $1)
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, userUuid uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByUser, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Label,
			&i.TokenHash,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, touchAPITokenLastUsed, id)
	return err
}
