// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: api_keys.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    name,
    key_hash,
    key_prefix,
    user_id,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, uuid, name, key_hash, key_prefix, user_id, expires_at, last_used_at, created_at, updated_at
`

type CreateAPIKeyParams struct {
	Name      string       `db:"name" json:"name"`
	KeyHash   string       `db:"key_hash" json:"key_hash"`
	KeyPrefix string       `db:"key_prefix" json:"key_prefix"`
	UserID    int32        `db:"user_id" json:"user_id"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.UserID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT ak.id, ak.uuid, ak.name, ak.key_hash, ak.key_prefix, ak.user_id, ak.expires_at, ak.last_used_at, ak.created_at, ak.updated_at, u.uuid as user_uuid, u.name as user_name, u.username, u.login_type, u.role
FROM api_keys ak
JOIN users u ON ak.user_id = u.id
WHERE ak.key_prefix = $1
`

type GetAPIKeyByPrefixRow struct {
	ID         int32         `db:"id" json:"id"`
	Uuid       uuid.UUID     `db:"uuid" json:"uuid"`
	Name       string        `db:"name" json:"name"`
	KeyHash    string        `db:"key_hash" json:"key_hash"`
	KeyPrefix  string        `db:"key_prefix" json:"key_prefix"`
	UserID     int32         `db:"user_id" json:"user_id"`
	ExpiresAt  sql.NullTime  `db:"expires_at" json:"expires_at"`
	LastUsedAt sql.NullTime  `db:"last_used_at" json:"last_used_at"`
	CreatedAt  time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time     `db:"updated_at" json:"updated_at"`
	UserUuid   uuid.UUID     `db:"user_uuid" json:"user_uuid"`
	UserName   string        `db:"user_name" json:"user_name"`
	Username   string        `db:"username" json:"username"`
	LoginType  UserLoginType `db:"login_type" json:"login_type"`
	Role       UserRoleType  `db:"role" json:"role"`
}

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (GetAPIKeyByPrefixRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByPrefix, keyPrefix)
	var i GetAPIKeyByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.UserID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
		&i.UserName,
		&i.Username,
		&i.LoginType,
		&i.Role,
	)
	return i, err
}

const getAPIKeysByUserUUID = `-- name: GetAPIKeysByUserUUID :many
SELECT ak.id, ak.uuid, ak.name, ak.key_hash, ak.key_prefix, ak.user_id, ak.expires_at, ak.last_used_at, ak.created_at, ak.updated_at
FROM api_keys ak
JOIN users u ON ak.user_id = u.id
WHERE u.uuid = $1
ORDER BY ak.created_at DESC
`

func (q *Queries) GetAPIKeysByUserUUID(ctx context.Context, userUUID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeysByUserUUID, userUUID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.UserID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPIKeyByUUID = `-- name: GetAPIKeyByUUID :one
SELECT id, uuid, name, key_hash, key_prefix, user_id, expires_at, last_used_at, created_at, updated_at FROM api_keys WHERE uuid = $1
`

func (q *Queries) GetAPIKeyByUUID(ctx context.Context, argUuid uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByUUID, argUuid)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.UserID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIKeyByUUID = `-- name: DeleteAPIKeyByUUID :exec
DELETE FROM api_keys WHERE uuid = $1
`

func (q *Queries) DeleteAPIKeyByUUID(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKeyByUUID, argUuid)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}

const getUserIDByUUID = `-- name: GetUserIDByUUID :one
SELECT id FROM users WHERE uuid = $1
`

func (q *Queries) GetUserIDByUUID(ctx context.Context, argUuid uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByUUID, argUuid)
	var id int32
	err := row.Scan(&id)
	return id, err
}
