// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: approvals.sql

package repo

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addApprovalRequest = `-- name: AddApprovalRequest :one
INSERT INTO approvals (
    exec_log_id,
    approvers,
    action_id
) VALUES (
    $1, $2, $3
) RETURNING id, uuid, exec_log_id, action_id, status, approvers, created_at, updated_at
`

type AddApprovalRequestParams struct {
	ExecLogID int32           `db:"exec_log_id" json:"exec_log_id"`
	Approvers json.RawMessage `db:"approvers" json:"approvers"`
	ActionID  string          `db:"action_id" json:"action_id"`
}

func (q *Queries) AddApprovalRequest(ctx context.Context, arg AddApprovalRequestParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, addApprovalRequest, arg.ExecLogID, arg.Approvers, arg.ActionID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExecLogID,
		&i.ActionID,
		&i.Status,
		&i.Approvers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const approveRequestByUUID = `-- name: ApproveRequestByUUID :one
UPDATE approvals SET status = 'approved', updated_at = NOW() WHERE uuid = $1 RETURNING id, uuid, exec_log_id, action_id, status, approvers, created_at, updated_at
`

func (q *Queries) ApproveRequestByUUID(ctx context.Context, argUuid uuid.UUID) (Approval, error) {
	row := q.db.QueryRowContext(ctx, approveRequestByUUID, argUuid)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExecLogID,
		&i.ActionID,
		&i.Status,
		&i.Approvers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalByUUID = `-- name: GetApprovalByUUID :one
SELECT id, uuid, exec_log_id, action_id, status, approvers, created_at, updated_at FROM approvals WHERE uuid = $1
`

func (q *Queries) GetApprovalByUUID(ctx context.Context, argUuid uuid.UUID) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalByUUID, argUuid)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExecLogID,
		&i.ActionID,
		&i.Status,
		&i.Approvers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalRequestsForActionAndExec = `-- name: GetApprovalRequestsForActionAndExec :one
WITH exec_lookup AS (
    SELECT id FROM execution_log WHERE exec_id = $1
)
SELECT id, uuid, exec_log_id, action_id, status, approvers, created_at, updated_at FROM approvals WHERE exec_log_id = (SELECT id FROM exec_lookup) AND action_id = $2
`

type GetApprovalRequestsForActionAndExecParams struct {
	ExecID   string `db:"exec_id" json:"exec_id"`
	ActionID string `db:"action_id" json:"action_id"`
}

func (q *Queries) GetApprovalRequestsForActionAndExec(ctx context.Context, arg GetApprovalRequestsForActionAndExecParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalRequestsForActionAndExec, arg.ExecID, arg.ActionID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExecLogID,
		&i.ActionID,
		&i.Status,
		&i.Approvers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectRequestByUUID = `-- name: RejectRequestByUUID :one
UPDATE approvals SET status = 'rejected', updated_at = NOW() WHERE uuid = $1 RETURNING id, uuid, exec_log_id, action_id, status, approvers, created_at, updated_at
`

func (q *Queries) RejectRequestByUUID(ctx context.Context, argUuid uuid.UUID) (Approval, error) {
	row := q.db.QueryRowContext(ctx, rejectRequestByUUID, argUuid)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExecLogID,
		&i.ActionID,
		&i.Status,
		&i.Approvers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApprovalStatusByUUID = `-- name: UpdateApprovalStatusByUUID :one
UPDATE approvals SET status = $1, updated_at = NOW() WHERE uuid = $1 RETURNING id, uuid, exec_log_id, action_id, status, approvers, created_at, updated_at
`

func (q *Queries) UpdateApprovalStatusByUUID(ctx context.Context, status ApprovalStatus) (Approval, error) {
	row := q.db.QueryRowContext(ctx, updateApprovalStatusByUUID, status)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExecLogID,
		&i.ActionID,
		&i.Status,
		&i.Approvers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
