// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: credentials.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (name, private_key, password)
VALUES ($1, $2, $3)
RETURNING id, uuid, name, private_key, password, created_at, updated_at
`

type CreateCredentialParams struct {
	Name       string         `db:"name" json:"name"`
	PrivateKey sql.NullString `db:"private_key" json:"private_key"`
	Password   sql.NullString `db:"password" json:"password"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential, arg.Name, arg.PrivateKey, arg.Password)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PrivateKey,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE uuid = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, argUuid)
	return err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, uuid, name, private_key, password, created_at, updated_at FROM credentials WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id int32) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PrivateKey,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByUUID = `-- name: GetCredentialByUUID :one
SELECT id, uuid, name, private_key, password, created_at, updated_at FROM credentials WHERE uuid = $1
`

func (q *Queries) GetCredentialByUUID(ctx context.Context, argUuid uuid.UUID) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByUUID, argUuid)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PrivateKey,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
WITH filtered AS (
    SELECT id, uuid, name, private_key, password, created_at, updated_at FROM credentials
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, uuid, name, private_key, password, created_at, updated_at FROM filtered
    ORDER BY created_at DESC
    LIMIT $1 OFFSET $2
),
page_count AS (
    SELECT COUNT(*) AS page_count FROM paged
)
SELECT
    p.id, p.uuid, p.name, p.private_key, p.password, p.created_at, p.updated_at,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListCredentialsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListCredentialsRow struct {
	ID         int32          `db:"id" json:"id"`
	Uuid       uuid.UUID      `db:"uuid" json:"uuid"`
	Name       string         `db:"name" json:"name"`
	PrivateKey sql.NullString `db:"private_key" json:"private_key"`
	Password   sql.NullString `db:"password" json:"password"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time      `db:"updated_at" json:"updated_at"`
	PageCount  int64          `db:"page_count" json:"page_count"`
	TotalCount int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListCredentials(ctx context.Context, arg ListCredentialsParams) ([]ListCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsRow
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.PrivateKey,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials
SET name = $2, private_key = $3, password = $4, updated_at = NOW()
WHERE uuid = $1
RETURNING id, uuid, name, private_key, password, created_at, updated_at
`

type UpdateCredentialParams struct {
	Uuid       uuid.UUID      `db:"uuid" json:"uuid"`
	Name       string         `db:"name" json:"name"`
	PrivateKey sql.NullString `db:"private_key" json:"private_key"`
	Password   sql.NullString `db:"password" json:"password"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, updateCredential,
		arg.Uuid,
		arg.Name,
		arg.PrivateKey,
		arg.Password,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PrivateKey,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
