// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: executor_kv.sql

package repo

import (
	"context"
)

const deleteExecutorKV = `-- name: DeleteExecutorKV :exec
DELETE FROM executor_kv_store
WHERE bucket = $1 AND key = $2
`

type DeleteExecutorKVParams struct {
	Bucket string `db:"bucket" json:"bucket"`
	Key    string `db:"key" json:"key"`
}

func (q *Queries) DeleteExecutorKV(ctx context.Context, arg DeleteExecutorKVParams) error {
	_, err := q.db.ExecContext(ctx, deleteExecutorKV, arg.Bucket, arg.Key)
	return err
}

const deleteExecutorKVByBucket = `-- name: DeleteExecutorKVByBucket :exec
DELETE FROM executor_kv_store
WHERE bucket = $1
`

func (q *Queries) DeleteExecutorKVByBucket(ctx context.Context, bucket string) error {
	_, err := q.db.ExecContext(ctx, deleteExecutorKVByBucket, bucket)
	return err
}

const getExecutorKV = `-- name: GetExecutorKV :one
SELECT id, uuid, bucket, key, value, created_at, updated_at
FROM executor_kv_store
WHERE bucket = $1 AND key = $2
`

type GetExecutorKVParams struct {
	Bucket string `db:"bucket" json:"bucket"`
	Key    string `db:"key" json:"key"`
}

func (q *Queries) GetExecutorKV(ctx context.Context, arg GetExecutorKVParams) (ExecutorKvStore, error) {
	row := q.db.QueryRowContext(ctx, getExecutorKV, arg.Bucket, arg.Key)
	var i ExecutorKvStore
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Bucket,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExecutorKVByBucket = `-- name: ListExecutorKVByBucket :many
SELECT id, uuid, bucket, key, value, created_at, updated_at
FROM executor_kv_store
WHERE bucket = $1
ORDER BY key
`

func (q *Queries) ListExecutorKVByBucket(ctx context.Context, bucket string) ([]ExecutorKvStore, error) {
	rows, err := q.db.QueryContext(ctx, listExecutorKVByBucket, bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutorKvStore
	for rows.Next() {
		var i ExecutorKvStore
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Bucket,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExecutorKV = `-- name: UpsertExecutorKV :one
INSERT INTO executor_kv_store (bucket, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (bucket, key) DO UPDATE
    SET value = EXCLUDED.value,
        updated_at = NOW()
RETURNING id, uuid, bucket, key, value, created_at, updated_at
`

type UpsertExecutorKVParams struct {
	Bucket string `db:"bucket" json:"bucket"`
	Key    string `db:"key" json:"key"`
	Value  string `db:"value" json:"value"`
}

func (q *Queries) UpsertExecutorKV(ctx context.Context, arg UpsertExecutorKVParams) (ExecutorKvStore, error) {
	row := q.db.QueryRowContext(ctx, upsertExecutorKV, arg.Bucket, arg.Key, arg.Value)
	var i ExecutorKvStore
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Bucket,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
