// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: execution.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addExecution = `-- name: AddExecution :one
WITH user_lookup AS (
    SELECT id FROM users WHERE users.uuid = $4
), namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $5
)
INSERT INTO executions (
    exec_id, flow_id, inputs, trigger_type, triggered_by, namespace_id, scheduled_at
) VALUES (
    $1, $2, $3, $6, (SELECT id FROM user_lookup), (SELECT id FROM namespace_lookup), $7
) RETURNING id, exec_id, flow_id, namespace_id, triggered_by, trigger_type, inputs, scheduled_at, created_at, attempt, status, error, outputs, started_at, completed_at, updated_at
`

type AddExecutionParams struct {
	ExecID      string          `db:"exec_id" json:"exec_id"`
	FlowID      int32           `db:"flow_id" json:"flow_id"`
	Inputs      json.RawMessage `db:"inputs" json:"inputs"`
	Uuid        uuid.UUID       `db:"uuid" json:"uuid"`
	Uuid_2      uuid.UUID       `db:"uuid_2" json:"uuid_2"`
	TriggerType TriggerType     `db:"trigger_type" json:"trigger_type"`
	ScheduledAt sql.NullTime    `db:"scheduled_at" json:"scheduled_at"`
}

func (q *Queries) AddExecution(ctx context.Context, arg AddExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, addExecution,
		arg.ExecID,
		arg.FlowID,
		arg.Inputs,
		arg.Uuid,
		arg.Uuid_2,
		arg.TriggerType,
		arg.ScheduledAt,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.NamespaceID,
		&i.TriggeredBy,
		&i.TriggerType,
		&i.Inputs,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.Attempt,
		&i.Status,
		&i.Error,
		&i.Outputs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const beginAttempt = `-- name: BeginAttempt :one
UPDATE executions SET attempt = attempt + 1, updated_at = NOW()
WHERE exec_id = $1 AND status IN ('pending', 'running', 'errored')
RETURNING attempt
`

func (q *Queries) BeginAttempt(ctx context.Context, execID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, beginAttempt, execID)
	var attempt int32
	err := row.Scan(&attempt)
	return attempt, err
}

const cancelExecution = `-- name: CancelExecution :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
UPDATE executions SET
    status = 'cancelled', completed_at = NOW(), updated_at = NOW(), attempt = attempt + 1
WHERE exec_id = $1
  AND namespace_id = (SELECT id FROM namespace_lookup)
  AND status IN ('pending', 'running', 'pending_approval')
RETURNING id, exec_id, flow_id, namespace_id, triggered_by, trigger_type, inputs, scheduled_at, created_at, attempt, status, error, outputs, started_at, completed_at, updated_at
`

type CancelExecutionParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) CancelExecution(ctx context.Context, arg CancelExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, cancelExecution, arg.ExecID, arg.Uuid)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.NamespaceID,
		&i.TriggeredBy,
		&i.TriggerType,
		&i.Inputs,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.Attempt,
		&i.Status,
		&i.Error,
		&i.Outputs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExecutionEventsByExecIDs = `-- name: DeleteExecutionEventsByExecIDs :exec
DELETE FROM execution_events WHERE exec_id = ANY($1::varchar[])
`

func (q *Queries) DeleteExecutionEventsByExecIDs(ctx context.Context, execIds []string) error {
	_, err := q.db.ExecContext(ctx, deleteExecutionEventsByExecIDs, pq.Array(execIds))
	return err
}

const deleteExpiredExecutions = `-- name: DeleteExpiredExecutions :many
WITH expired AS (
    SELECT exec_id FROM executions
    WHERE status IN ('completed', 'errored', 'cancelled')
      AND COALESCE(executions.completed_at, executions.updated_at) < $1
    ORDER BY COALESCE(executions.completed_at, executions.updated_at)
    LIMIT $2
)
DELETE FROM executions
WHERE exec_id IN (SELECT exec_id FROM expired)
  AND status IN ('completed', 'errored', 'cancelled')
RETURNING exec_id
`

type DeleteExpiredExecutionsParams struct {
	Cutoff    sql.NullTime `db:"cutoff" json:"cutoff"`
	BatchSize int32        `db:"batch_size" json:"batch_size"`
}

func (q *Queries) DeleteExpiredExecutions(ctx context.Context, arg DeleteExpiredExecutionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredExecutions, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var exec_id string
		if err := rows.Scan(&exec_id); err != nil {
			return nil, err
		}
		items = append(items, exec_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const executionExistsForFlow = `-- name: ExecutionExistsForFlow :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT EXISTS (
    SELECT 1 FROM executions
    WHERE flow_id = (
        SELECT id FROM flows
        WHERE slug = $1 AND namespace_id = (SELECT id FROM namespace_lookup) AND is_active = TRUE
    )
      AND namespace_id = (SELECT id FROM namespace_lookup)
      AND status IN ('running', 'pending_approval', 'pending')
)
`

type ExecutionExistsForFlowParams struct {
	Slug string    `db:"slug" json:"slug"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) ExecutionExistsForFlow(ctx context.Context, arg ExecutionExistsForFlowParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, executionExistsForFlow, arg.Slug, arg.Uuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllExecutionsPaginated = `-- name: GetAllExecutionsPaginated :many
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $1
), filtered AS (
    SELECT el.id, el.exec_id, el.flow_id, el.namespace_id, el.triggered_by, el.trigger_type, el.inputs, el.scheduled_at, el.created_at, el.attempt, el.status, el.error, el.outputs, el.started_at, el.completed_at, el.updated_at, u.name, u.username, u.uuid AS triggered_by_uuid,
           CONCAT(u.name, ' <', u.username, '>')::TEXT AS triggered_by_name,
           f.name AS flow_name, f.slug AS flow_slug
    FROM executions el
    JOIN flows f ON el.flow_id = f.id
    JOIN users u ON el.triggered_by = u.id
    WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
      AND (el.scheduled_at IS NULL OR el.scheduled_at <= NOW())
), total AS (
    SELECT COUNT(*) AS total_count FROM filtered
), paged AS (
    SELECT id, exec_id, flow_id, namespace_id, triggered_by, trigger_type, inputs, scheduled_at, created_at, attempt, status, error, outputs, started_at, completed_at, updated_at, name, username, triggered_by_uuid, triggered_by_name, flow_name, flow_slug FROM filtered ORDER BY created_at DESC LIMIT $2 OFFSET $3
), page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT p.id, p.exec_id, p.flow_id, p.namespace_id, p.triggered_by, p.trigger_type, p.inputs, p.scheduled_at, p.created_at, p.attempt, p.status, p.error, p.outputs, p.started_at, p.completed_at, p.updated_at, p.name, p.username, p.triggered_by_uuid, p.triggered_by_name, p.flow_name, p.flow_slug, pc.page_count, t.total_count FROM paged p, page_count pc, total t
`

type GetAllExecutionsPaginatedParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type GetAllExecutionsPaginatedRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	TriggerType     TriggerType     `db:"trigger_type" json:"trigger_type"`
	Inputs          json.RawMessage `db:"inputs" json:"inputs"`
	ScheduledAt     sql.NullTime    `db:"scheduled_at" json:"scheduled_at"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	Status          ExecutionStatus `db:"status" json:"status"`
	Error           sql.NullString  `db:"error" json:"error"`
	Outputs         json.RawMessage `db:"outputs" json:"outputs"`
	StartedAt       sql.NullTime    `db:"started_at" json:"started_at"`
	CompletedAt     sql.NullTime    `db:"completed_at" json:"completed_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	Name            string          `db:"name" json:"name"`
	Username        string          `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string          `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string          `db:"flow_name" json:"flow_name"`
	FlowSlug        string          `db:"flow_slug" json:"flow_slug"`
	PageCount       int64           `db:"page_count" json:"page_count"`
	TotalCount      int64           `db:"total_count" json:"total_count"`
}

func (q *Queries) GetAllExecutionsPaginated(ctx context.Context, arg GetAllExecutionsPaginatedParams) ([]GetAllExecutionsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllExecutionsPaginated, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllExecutionsPaginatedRow
	for rows.Next() {
		var i GetAllExecutionsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.NamespaceID,
			&i.TriggeredBy,
			&i.TriggerType,
			&i.Inputs,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.Attempt,
			&i.Status,
			&i.Error,
			&i.Outputs,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Username,
			&i.TriggeredByUuid,
			&i.TriggeredByName,
			&i.FlowName,
			&i.FlowSlug,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionByExecID = `-- name: GetExecutionByExecID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT el.id, el.exec_id, el.flow_id, el.namespace_id, el.triggered_by, el.trigger_type, el.inputs, el.scheduled_at, el.created_at, el.attempt, el.status, el.error, el.outputs, el.started_at, el.completed_at, el.updated_at, u.name, u.username, u.uuid AS triggered_by_uuid,
       CONCAT(u.name, ' <', u.username, '>')::TEXT AS triggered_by_name,
       f.name AS flow_name, f.slug AS flow_slug
FROM executions el
JOIN users u ON el.triggered_by = u.id
JOIN flows f ON el.flow_id = f.id
WHERE el.exec_id = $1
  AND el.namespace_id = (SELECT id FROM namespace_lookup)
  AND f.is_active = TRUE
`

type GetExecutionByExecIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

type GetExecutionByExecIDRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	TriggerType     TriggerType     `db:"trigger_type" json:"trigger_type"`
	Inputs          json.RawMessage `db:"inputs" json:"inputs"`
	ScheduledAt     sql.NullTime    `db:"scheduled_at" json:"scheduled_at"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	Status          ExecutionStatus `db:"status" json:"status"`
	Error           sql.NullString  `db:"error" json:"error"`
	Outputs         json.RawMessage `db:"outputs" json:"outputs"`
	StartedAt       sql.NullTime    `db:"started_at" json:"started_at"`
	CompletedAt     sql.NullTime    `db:"completed_at" json:"completed_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	Name            string          `db:"name" json:"name"`
	Username        string          `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string          `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string          `db:"flow_name" json:"flow_name"`
	FlowSlug        string          `db:"flow_slug" json:"flow_slug"`
}

func (q *Queries) GetExecutionByExecID(ctx context.Context, arg GetExecutionByExecIDParams) (GetExecutionByExecIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByExecID, arg.ExecID, arg.Uuid)
	var i GetExecutionByExecIDRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.NamespaceID,
		&i.TriggeredBy,
		&i.TriggerType,
		&i.Inputs,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.Attempt,
		&i.Status,
		&i.Error,
		&i.Outputs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Username,
		&i.TriggeredByUuid,
		&i.TriggeredByName,
		&i.FlowName,
		&i.FlowSlug,
	)
	return i, err
}

const getExecutionByExecIDWithNamespace = `-- name: GetExecutionByExecIDWithNamespace :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT el.id, el.exec_id, el.flow_id, el.namespace_id, el.triggered_by, el.trigger_type, el.inputs, el.scheduled_at, el.created_at, el.attempt, el.status, el.error, el.outputs, el.started_at, el.completed_at, el.updated_at, u.name, u.username, u.uuid AS triggered_by_uuid,
       CONCAT(u.name, ' <', u.username, '>')::TEXT AS triggered_by_name,
       f.name AS flow_name, f.slug AS flow_slug
FROM executions el
JOIN users u ON el.triggered_by = u.id
JOIN flows f ON el.flow_id = f.id
WHERE el.exec_id = $1
  AND f.namespace_id = (SELECT id FROM namespace_lookup)
  AND f.is_active = TRUE
`

type GetExecutionByExecIDWithNamespaceParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

type GetExecutionByExecIDWithNamespaceRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	TriggerType     TriggerType     `db:"trigger_type" json:"trigger_type"`
	Inputs          json.RawMessage `db:"inputs" json:"inputs"`
	ScheduledAt     sql.NullTime    `db:"scheduled_at" json:"scheduled_at"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	Status          ExecutionStatus `db:"status" json:"status"`
	Error           sql.NullString  `db:"error" json:"error"`
	Outputs         json.RawMessage `db:"outputs" json:"outputs"`
	StartedAt       sql.NullTime    `db:"started_at" json:"started_at"`
	CompletedAt     sql.NullTime    `db:"completed_at" json:"completed_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	Name            string          `db:"name" json:"name"`
	Username        string          `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string          `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string          `db:"flow_name" json:"flow_name"`
	FlowSlug        string          `db:"flow_slug" json:"flow_slug"`
}

func (q *Queries) GetExecutionByExecIDWithNamespace(ctx context.Context, arg GetExecutionByExecIDWithNamespaceParams) (GetExecutionByExecIDWithNamespaceRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByExecIDWithNamespace, arg.ExecID, arg.Uuid)
	var i GetExecutionByExecIDWithNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.NamespaceID,
		&i.TriggeredBy,
		&i.TriggerType,
		&i.Inputs,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.Attempt,
		&i.Status,
		&i.Error,
		&i.Outputs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Username,
		&i.TriggeredByUuid,
		&i.TriggeredByName,
		&i.FlowName,
		&i.FlowSlug,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT el.id, el.exec_id, el.flow_id, el.namespace_id, el.triggered_by, el.trigger_type, el.inputs, el.scheduled_at, el.created_at, el.attempt, el.status, el.error, el.outputs, el.started_at, el.completed_at, el.updated_at, u.name, u.username, u.uuid AS triggered_by_uuid,
       CONCAT(u.name, ' <', u.username, '>')::TEXT AS triggered_by_name,
       f.name AS flow_name, f.slug AS flow_slug
FROM executions el
JOIN users u ON el.triggered_by = u.id
JOIN flows f ON el.flow_id = f.id
WHERE el.id = $1
  AND el.namespace_id = (SELECT id FROM namespace_lookup)
  AND f.is_active = TRUE
`

type GetExecutionByIDParams struct {
	ID   int32     `db:"id" json:"id"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

type GetExecutionByIDRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	TriggerType     TriggerType     `db:"trigger_type" json:"trigger_type"`
	Inputs          json.RawMessage `db:"inputs" json:"inputs"`
	ScheduledAt     sql.NullTime    `db:"scheduled_at" json:"scheduled_at"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	Status          ExecutionStatus `db:"status" json:"status"`
	Error           sql.NullString  `db:"error" json:"error"`
	Outputs         json.RawMessage `db:"outputs" json:"outputs"`
	StartedAt       sql.NullTime    `db:"started_at" json:"started_at"`
	CompletedAt     sql.NullTime    `db:"completed_at" json:"completed_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	Name            string          `db:"name" json:"name"`
	Username        string          `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string          `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string          `db:"flow_name" json:"flow_name"`
	FlowSlug        string          `db:"flow_slug" json:"flow_slug"`
}

func (q *Queries) GetExecutionByID(ctx context.Context, arg GetExecutionByIDParams) (GetExecutionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByID, arg.ID, arg.Uuid)
	var i GetExecutionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.NamespaceID,
		&i.TriggeredBy,
		&i.TriggerType,
		&i.Inputs,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.Attempt,
		&i.Status,
		&i.Error,
		&i.Outputs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Username,
		&i.TriggeredByUuid,
		&i.TriggeredByName,
		&i.FlowName,
		&i.FlowSlug,
	)
	return i, err
}

const getExecutionContextByUUID = `-- name: GetExecutionContextByUUID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT jsonb_build_object('inputs', inputs, 'outputs', outputs)::jsonb AS context
FROM executions
WHERE exec_id = $1 AND namespace_id = (SELECT id FROM namespace_lookup)
`

type GetExecutionContextByUUIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetExecutionContextByUUID(ctx context.Context, arg GetExecutionContextByUUIDParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getExecutionContextByUUID, arg.ExecID, arg.Uuid)
	var context json.RawMessage
	err := row.Scan(&context)
	return context, err
}

const getExecutionProjection = `-- name: GetExecutionProjection :one
SELECT id, exec_id, flow_id, namespace_id, triggered_by, trigger_type, inputs, scheduled_at, created_at, attempt, status, error, outputs, started_at, completed_at, updated_at FROM executions WHERE exec_id = $1
`

func (q *Queries) GetExecutionProjection(ctx context.Context, execID string) (Execution, error) {
	row := q.db.QueryRowContext(ctx, getExecutionProjection, execID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.NamespaceID,
		&i.TriggeredBy,
		&i.TriggerType,
		&i.Inputs,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.Attempt,
		&i.Status,
		&i.Error,
		&i.Outputs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionsByFlow = `-- name: GetExecutionsByFlow :many
WITH user_lookup AS (
    SELECT id FROM users WHERE users.uuid = $2
), namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $3
)
SELECT el.id, el.exec_id, el.flow_id, el.namespace_id, el.triggered_by, el.trigger_type, el.inputs, el.scheduled_at, el.created_at, el.attempt, el.status, el.error, el.outputs, el.started_at, el.completed_at, el.updated_at, u.name, u.username, u.uuid AS triggered_by_uuid,
       CONCAT(u.name, ' <', u.username, '>')::TEXT AS triggered_by_name,
       f.name AS flow_name, f.slug AS flow_slug
FROM executions el
JOIN flows f ON el.flow_id = f.id
JOIN users u ON el.triggered_by = u.id
WHERE f.id = $1
  AND el.triggered_by = (SELECT id FROM user_lookup)
  AND f.namespace_id = (SELECT id FROM namespace_lookup)
  AND f.is_active = TRUE
`

type GetExecutionsByFlowParams struct {
	ID     int32     `db:"id" json:"id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetExecutionsByFlowRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	TriggerType     TriggerType     `db:"trigger_type" json:"trigger_type"`
	Inputs          json.RawMessage `db:"inputs" json:"inputs"`
	ScheduledAt     sql.NullTime    `db:"scheduled_at" json:"scheduled_at"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	Status          ExecutionStatus `db:"status" json:"status"`
	Error           sql.NullString  `db:"error" json:"error"`
	Outputs         json.RawMessage `db:"outputs" json:"outputs"`
	StartedAt       sql.NullTime    `db:"started_at" json:"started_at"`
	CompletedAt     sql.NullTime    `db:"completed_at" json:"completed_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	Name            string          `db:"name" json:"name"`
	Username        string          `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string          `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string          `db:"flow_name" json:"flow_name"`
	FlowSlug        string          `db:"flow_slug" json:"flow_slug"`
}

func (q *Queries) GetExecutionsByFlow(ctx context.Context, arg GetExecutionsByFlowParams) ([]GetExecutionsByFlowRow, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByFlow, arg.ID, arg.Uuid, arg.Uuid_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExecutionsByFlowRow
	for rows.Next() {
		var i GetExecutionsByFlowRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.NamespaceID,
			&i.TriggeredBy,
			&i.TriggerType,
			&i.Inputs,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.Attempt,
			&i.Status,
			&i.Error,
			&i.Outputs,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Username,
			&i.TriggeredByUuid,
			&i.TriggeredByName,
			&i.FlowName,
			&i.FlowSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionsByFlowPaginated = `-- name: GetExecutionsByFlowPaginated :many
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
), user_namespaces AS (
    SELECT n.uuid, n.name, nm.role
    FROM namespaces n
    JOIN namespace_members nm ON n.id = nm.namespace_id
    JOIN users u ON nm.user_id = u.id
    WHERE u.uuid = $5 AND n.uuid = $2
    UNION
    SELECT DISTINCT n.uuid, n.name, nm.role
    FROM namespaces n
    JOIN namespace_members nm ON n.id = nm.namespace_id
    JOIN groups g ON nm.group_id = g.id
    JOIN group_memberships gm ON g.id = gm.group_id
    WHERE gm.user_id = (SELECT id FROM users WHERE users.uuid = $5) AND n.uuid = $2
), filtered AS (
    SELECT el.id, el.exec_id, el.flow_id, el.namespace_id, el.triggered_by, el.trigger_type, el.inputs, el.scheduled_at, el.created_at, el.attempt, el.status, el.error, el.outputs, el.started_at, el.completed_at, el.updated_at, u.name, u.username, u.uuid AS triggered_by_uuid,
           CONCAT(u.name, ' <', u.username, '>')::TEXT AS triggered_by_name,
           f.name AS flow_name, f.slug AS flow_slug
    FROM executions el
    JOIN flows f ON el.flow_id = f.id
    JOIN users u ON el.triggered_by = u.id
    WHERE f.id = $1
      AND f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
      AND (el.scheduled_at IS NULL OR el.scheduled_at <= NOW())
      AND (
        el.triggered_by = (SELECT id FROM users WHERE users.uuid = $5)
        OR EXISTS (SELECT id FROM users WHERE users.uuid = $5 AND users.role = 'superuser')
        OR EXISTS (SELECT uuid FROM user_namespaces WHERE role IN ('admin', 'reviewer', 'operator'))
      )
), total AS (
    SELECT COUNT(*) AS total_count FROM filtered
), paged AS (
    SELECT id, exec_id, flow_id, namespace_id, triggered_by, trigger_type, inputs, scheduled_at, created_at, attempt, status, error, outputs, started_at, completed_at, updated_at, name, username, triggered_by_uuid, triggered_by_name, flow_name, flow_slug FROM filtered ORDER BY created_at DESC LIMIT $3 OFFSET $4
), page_count AS (
    SELECT CEIL(total.total_count::numeric / $3::numeric)::bigint AS page_count FROM total
)
SELECT p.id, p.exec_id, p.flow_id, p.namespace_id, p.triggered_by, p.trigger_type, p.inputs, p.scheduled_at, p.created_at, p.attempt, p.status, p.error, p.outputs, p.started_at, p.completed_at, p.updated_at, p.name, p.username, p.triggered_by_uuid, p.triggered_by_name, p.flow_name, p.flow_slug, pc.page_count, t.total_count FROM paged p, page_count pc, total t
`

type GetExecutionsByFlowPaginatedParams struct {
	ID     int32     `db:"id" json:"id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetExecutionsByFlowPaginatedRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	TriggerType     TriggerType     `db:"trigger_type" json:"trigger_type"`
	Inputs          json.RawMessage `db:"inputs" json:"inputs"`
	ScheduledAt     sql.NullTime    `db:"scheduled_at" json:"scheduled_at"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	Status          ExecutionStatus `db:"status" json:"status"`
	Error           sql.NullString  `db:"error" json:"error"`
	Outputs         json.RawMessage `db:"outputs" json:"outputs"`
	StartedAt       sql.NullTime    `db:"started_at" json:"started_at"`
	CompletedAt     sql.NullTime    `db:"completed_at" json:"completed_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	Name            string          `db:"name" json:"name"`
	Username        string          `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string          `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string          `db:"flow_name" json:"flow_name"`
	FlowSlug        string          `db:"flow_slug" json:"flow_slug"`
	PageCount       int64           `db:"page_count" json:"page_count"`
	TotalCount      int64           `db:"total_count" json:"total_count"`
}

func (q *Queries) GetExecutionsByFlowPaginated(ctx context.Context, arg GetExecutionsByFlowPaginatedParams) ([]GetExecutionsByFlowPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByFlowPaginated,
		arg.ID,
		arg.Uuid,
		arg.Limit,
		arg.Offset,
		arg.Uuid_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExecutionsByFlowPaginatedRow
	for rows.Next() {
		var i GetExecutionsByFlowPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.NamespaceID,
			&i.TriggeredBy,
			&i.TriggerType,
			&i.Inputs,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.Attempt,
			&i.Status,
			&i.Error,
			&i.Outputs,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Username,
			&i.TriggeredByUuid,
			&i.TriggeredByName,
			&i.FlowName,
			&i.FlowSlug,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowFromExecID = `-- name: GetFlowFromExecID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id FROM flows f
JOIN executions el ON el.flow_id = f.id
WHERE el.exec_id = $1
  AND f.namespace_id = (SELECT id FROM namespace_lookup)
  AND f.is_active = TRUE
`

type GetFlowFromExecIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetFlowFromExecID(ctx context.Context, arg GetFlowFromExecIDParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowFromExecID, arg.ExecID, arg.Uuid)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.FilePath,
		&i.NamespaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrefixID,
	)
	return i, err
}

const getFlowFromExecIDWithNamespace = `-- name: GetFlowFromExecIDWithNamespace :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id FROM flows f
JOIN executions el ON el.flow_id = f.id
WHERE el.exec_id = $1
  AND f.namespace_id = (SELECT id FROM namespace_lookup)
  AND f.is_active = TRUE
`

type GetFlowFromExecIDWithNamespaceParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetFlowFromExecIDWithNamespace(ctx context.Context, arg GetFlowFromExecIDWithNamespaceParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowFromExecIDWithNamespace, arg.ExecID, arg.Uuid)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.FilePath,
		&i.NamespaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrefixID,
	)
	return i, err
}

const getScheduledExecutionsByFlow = `-- name: GetScheduledExecutionsByFlow :many
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT el.exec_id, el.scheduled_at
FROM executions el
JOIN flows f ON el.flow_id = f.id
WHERE el.flow_id = $1
  AND f.namespace_id = (SELECT id FROM namespace_lookup)
  AND f.is_active = TRUE
  AND el.scheduled_at IS NOT NULL
  AND el.scheduled_at > NOW()
  AND el.status = 'pending'
ORDER BY el.scheduled_at
`

type GetScheduledExecutionsByFlowParams struct {
	FlowID int32     `db:"flow_id" json:"flow_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

type GetScheduledExecutionsByFlowRow struct {
	ExecID      string       `db:"exec_id" json:"exec_id"`
	ScheduledAt sql.NullTime `db:"scheduled_at" json:"scheduled_at"`
}

func (q *Queries) GetScheduledExecutionsByFlow(ctx context.Context, arg GetScheduledExecutionsByFlowParams) ([]GetScheduledExecutionsByFlowRow, error) {
	rows, err := q.db.QueryContext(ctx, getScheduledExecutionsByFlow, arg.FlowID, arg.Uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScheduledExecutionsByFlowRow
	for rows.Next() {
		var i GetScheduledExecutionsByFlowRow
		if err := rows.Scan(&i.ExecID, &i.ScheduledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertExecutionEvent = `-- name: InsertExecutionEvent :execrows
INSERT INTO execution_events (exec_id, attempt, action_id, type, error, outputs, created_at)
SELECT $1::varchar AS exec_id,
       $2::integer AS attempt,
       $3::varchar AS action_id,
       $4::execution_event_type AS type,
       $5::text AS error,
       $6::jsonb AS outputs,
       COALESCE($7::timestamptz, NOW()) AS created_at
WHERE EXISTS (
    SELECT 1 FROM executions
    WHERE exec_id = $1 AND attempt = $2
)
`

type InsertExecutionEventParams struct {
	ExecID    string                `db:"exec_id" json:"exec_id"`
	Attempt   int32                 `db:"attempt" json:"attempt"`
	ActionID  sql.NullString        `db:"action_id" json:"action_id"`
	EventType ExecutionEventType    `db:"event_type" json:"event_type"`
	Error     sql.NullString        `db:"error" json:"error"`
	Outputs   pqtype.NullRawMessage `db:"outputs" json:"outputs"`
	CreatedAt sql.NullTime          `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertExecutionEvent(ctx context.Context, arg InsertExecutionEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertExecutionEvent,
		arg.ExecID,
		arg.Attempt,
		arg.ActionID,
		arg.EventType,
		arg.Error,
		arg.Outputs,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listExecutionIDs = `-- name: ListExecutionIDs :many
SELECT exec_id FROM executions ORDER BY exec_id
`

func (q *Queries) ListExecutionIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var exec_id string
		if err := rows.Scan(&exec_id); err != nil {
			return nil, err
		}
		items = append(items, exec_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadExecutionEvents = `-- name: LoadExecutionEvents :many
SELECT seq, exec_id, attempt, action_id, type, error, outputs, created_at FROM execution_events WHERE exec_id = $1 ORDER BY seq
`

func (q *Queries) LoadExecutionEvents(ctx context.Context, execID string) ([]ExecutionEvent, error) {
	rows, err := q.db.QueryContext(ctx, loadExecutionEvents, execID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionEvent
	for rows.Next() {
		var i ExecutionEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ExecID,
			&i.Attempt,
			&i.ActionID,
			&i.Type,
			&i.Error,
			&i.Outputs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExecutionEvent = `-- name: ProjectExecutionEvent :execresult
UPDATE executions SET
    status = CASE $1::execution_event_type
        WHEN 'queued' THEN 'pending'::execution_status
        WHEN 'started' THEN 'running'::execution_status
        WHEN 'waiting_approval' THEN 'pending_approval'::execution_status
        WHEN 'completed' THEN 'completed'::execution_status
        WHEN 'errored' THEN 'errored'::execution_status
        WHEN 'cancelled' THEN 'cancelled'::execution_status
        ELSE status
    END,
    error = CASE
        WHEN $1::execution_event_type IN ('queued', 'started') THEN NULL
        WHEN $1::execution_event_type IN ('completed', 'errored', 'cancelled') THEN $2
        ELSE error
    END,
    outputs = CASE WHEN $3::jsonb IS NOT NULL
        THEN outputs || $3::jsonb ELSE outputs END,
    started_at = CASE WHEN $1::execution_event_type = 'started'
        THEN COALESCE(started_at, COALESCE($4, NOW())) ELSE started_at END,
    completed_at = CASE
        WHEN $1::execution_event_type IN ('queued', 'started') THEN NULL
        WHEN $1::execution_event_type IN ('completed', 'errored', 'cancelled')
            THEN COALESCE($4, NOW())
        ELSE completed_at
    END,
    updated_at = NOW()
WHERE exec_id = $5 AND attempt = $6
`

type ProjectExecutionEventParams struct {
	EventType ExecutionEventType    `db:"event_type" json:"event_type"`
	Error     sql.NullString        `db:"error" json:"error"`
	Outputs   pqtype.NullRawMessage `db:"outputs" json:"outputs"`
	CreatedAt sql.NullTime          `db:"created_at" json:"created_at"`
	ExecID    string                `db:"exec_id" json:"exec_id"`
	Attempt   int32                 `db:"attempt" json:"attempt"`
}

func (q *Queries) ProjectExecutionEvent(ctx context.Context, arg ProjectExecutionEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, projectExecutionEvent,
		arg.EventType,
		arg.Error,
		arg.Outputs,
		arg.CreatedAt,
		arg.ExecID,
		arg.Attempt,
	)
}

const requeueExecution = `-- name: RequeueExecution :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
UPDATE executions SET status = 'pending', updated_at = NOW()
WHERE exec_id = $1
  AND namespace_id = (SELECT id FROM namespace_lookup)
  AND status IN ('errored', 'cancelled', 'pending_approval')
RETURNING attempt
`

type RequeueExecutionParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) RequeueExecution(ctx context.Context, arg RequeueExecutionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, requeueExecution, arg.ExecID, arg.Uuid)
	var attempt int32
	err := row.Scan(&attempt)
	return attempt, err
}

const searchExecutionsPaginated = `-- name: SearchExecutionsPaginated :many
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $1
), user_namespaces AS (
    SELECT n.uuid, n.name, nm.role
    FROM namespaces n
    JOIN namespace_members nm ON n.id = nm.namespace_id
    JOIN users u ON nm.user_id = u.id
    WHERE u.uuid = $5 AND n.uuid = $1
    UNION
    SELECT DISTINCT n.uuid, n.name, nm.role
    FROM namespaces n
    JOIN namespace_members nm ON n.id = nm.namespace_id
    JOIN groups g ON nm.group_id = g.id
    JOIN group_memberships gm ON g.id = gm.group_id
    WHERE gm.user_id = (SELECT id FROM users WHERE users.uuid = $5) AND n.uuid = $1
), filtered AS (
    SELECT el.id, el.exec_id, el.flow_id, el.namespace_id, el.triggered_by, el.trigger_type, el.inputs, el.scheduled_at, el.created_at, el.attempt, el.status, el.error, el.outputs, el.started_at, el.completed_at, el.updated_at, u.name, u.username, u.uuid AS triggered_by_uuid,
           CONCAT(u.name, ' <', u.username, '>')::TEXT AS triggered_by_name,
           f.name AS flow_name, f.slug AS flow_slug
    FROM executions el
    JOIN flows f ON el.flow_id = f.id
    JOIN users u ON el.triggered_by = u.id
    WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
      AND (el.scheduled_at IS NULL OR el.scheduled_at <= NOW())
      AND (
        el.triggered_by = (SELECT id FROM users WHERE users.uuid = $5)
        OR EXISTS (SELECT id FROM users WHERE users.uuid = $5 AND users.role = 'superuser')
        OR EXISTS (SELECT uuid FROM user_namespaces WHERE role IN ('admin', 'reviewer', 'operator'))
      )
      AND ($2 = '' OR f.name ILIKE '%' || $2 || '%' OR f.slug ILIKE '%' || $2 || '%'
        OR el.exec_id ILIKE '%' || $2 || '%' OR u.name ILIKE '%' || $2 || '%'
        OR u.username ILIKE '%' || $2 || '%')
), total AS (
    SELECT COUNT(*) AS total_count FROM filtered
), paged AS (
    SELECT id, exec_id, flow_id, namespace_id, triggered_by, trigger_type, inputs, scheduled_at, created_at, attempt, status, error, outputs, started_at, completed_at, updated_at, name, username, triggered_by_uuid, triggered_by_name, flow_name, flow_slug FROM filtered ORDER BY created_at DESC LIMIT $3 OFFSET $4
), page_count AS (
    SELECT CEIL(total.total_count::numeric / $3::numeric)::bigint AS page_count FROM total
)
SELECT p.id, p.exec_id, p.flow_id, p.namespace_id, p.triggered_by, p.trigger_type, p.inputs, p.scheduled_at, p.created_at, p.attempt, p.status, p.error, p.outputs, p.started_at, p.completed_at, p.updated_at, p.name, p.username, p.triggered_by_uuid, p.triggered_by_name, p.flow_name, p.flow_slug, pc.page_count, t.total_count FROM paged p, page_count pc, total t
`

type SearchExecutionsPaginatedParams struct {
	Uuid    uuid.UUID   `db:"uuid" json:"uuid"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
	Uuid_2  uuid.UUID   `db:"uuid_2" json:"uuid_2"`
}

type SearchExecutionsPaginatedRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	TriggerType     TriggerType     `db:"trigger_type" json:"trigger_type"`
	Inputs          json.RawMessage `db:"inputs" json:"inputs"`
	ScheduledAt     sql.NullTime    `db:"scheduled_at" json:"scheduled_at"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	Attempt         int32           `db:"attempt" json:"attempt"`
	Status          ExecutionStatus `db:"status" json:"status"`
	Error           sql.NullString  `db:"error" json:"error"`
	Outputs         json.RawMessage `db:"outputs" json:"outputs"`
	StartedAt       sql.NullTime    `db:"started_at" json:"started_at"`
	CompletedAt     sql.NullTime    `db:"completed_at" json:"completed_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	Name            string          `db:"name" json:"name"`
	Username        string          `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string          `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string          `db:"flow_name" json:"flow_name"`
	FlowSlug        string          `db:"flow_slug" json:"flow_slug"`
	PageCount       int64           `db:"page_count" json:"page_count"`
	TotalCount      int64           `db:"total_count" json:"total_count"`
}

func (q *Queries) SearchExecutionsPaginated(ctx context.Context, arg SearchExecutionsPaginatedParams) ([]SearchExecutionsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, searchExecutionsPaginated,
		arg.Uuid,
		arg.Column2,
		arg.Limit,
		arg.Offset,
		arg.Uuid_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchExecutionsPaginatedRow
	for rows.Next() {
		var i SearchExecutionsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.NamespaceID,
			&i.TriggeredBy,
			&i.TriggerType,
			&i.Inputs,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.Attempt,
			&i.Status,
			&i.Error,
			&i.Outputs,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Username,
			&i.TriggeredByUuid,
			&i.TriggeredByName,
			&i.FlowName,
			&i.FlowSlug,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutionProjection = `-- name: UpdateExecutionProjection :exec
UPDATE executions SET status = $2, error = $3, outputs = $4, started_at = $5,
    completed_at = $6, updated_at = NOW()
WHERE exec_id = $1
`

type UpdateExecutionProjectionParams struct {
	ExecID      string          `db:"exec_id" json:"exec_id"`
	Status      ExecutionStatus `db:"status" json:"status"`
	Error       sql.NullString  `db:"error" json:"error"`
	Outputs     json.RawMessage `db:"outputs" json:"outputs"`
	StartedAt   sql.NullTime    `db:"started_at" json:"started_at"`
	CompletedAt sql.NullTime    `db:"completed_at" json:"completed_at"`
}

func (q *Queries) UpdateExecutionProjection(ctx context.Context, arg UpdateExecutionProjectionParams) error {
	_, err := q.db.ExecContext(ctx, updateExecutionProjection,
		arg.ExecID,
		arg.Status,
		arg.Error,
		arg.Outputs,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}
