// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: execution.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addExecutionLog = `-- name: AddExecutionLog :one
WITH user_lookup AS (
    SELECT id FROM users WHERE users.uuid = $5
), namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $6
)
INSERT INTO execution_log (
    exec_id,
    parent_exec_id,
    flow_id,
    input,
    triggered_by,
    namespace_id
) VALUES (
    $1, $2, $3, $4, (SELECT id FROM user_lookup), (SELECT id FROM namespace_lookup)
) RETURNING id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, namespace_id, created_at, updated_at
`

type AddExecutionLogParams struct {
	ExecID       string          `db:"exec_id" json:"exec_id"`
	ParentExecID sql.NullString  `db:"parent_exec_id" json:"parent_exec_id"`
	FlowID       int32           `db:"flow_id" json:"flow_id"`
	Input        json.RawMessage `db:"input" json:"input"`
	Uuid         uuid.UUID       `db:"uuid" json:"uuid"`
	Uuid_2       uuid.UUID       `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) AddExecutionLog(ctx context.Context, arg AddExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, addExecutionLog,
		arg.ExecID,
		arg.ParentExecID,
		arg.FlowID,
		arg.Input,
		arg.Uuid,
		arg.Uuid_2,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChildrenByParentUUID = `-- name: GetChildrenByParentUUID :many
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, namespace_id, created_at, updated_at FROM execution_log 
WHERE execution_log.parent_exec_id = $1 AND execution_log.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetChildrenByParentUUIDParams struct {
	ParentExecID sql.NullString `db:"parent_exec_id" json:"parent_exec_id"`
	Uuid         uuid.UUID      `db:"uuid" json:"uuid"`
}

func (q *Queries) GetChildrenByParentUUID(ctx context.Context, arg GetChildrenByParentUUIDParams) ([]ExecutionLog, error) {
	rows, err := q.db.QueryContext(ctx, getChildrenByParentUUID, arg.ParentExecID, arg.Uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionLog
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.ParentExecID,
			&i.Input,
			&i.Error,
			&i.Status,
			&i.TriggeredBy,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionByExecID = `-- name: GetExecutionByExecID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT
    el.id, el.exec_id, el.flow_id, el.parent_exec_id, el.input, el.error, el.status, el.triggered_by, el.namespace_id, el.created_at, el.updated_at,
    u.uuid AS triggered_by_uuid
FROM
    execution_log el
INNER JOIN
    users u ON el.triggered_by = u.id
WHERE
    el.exec_id = $1
    AND el.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetExecutionByExecIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

type GetExecutionByExecIDRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	ParentExecID    sql.NullString  `db:"parent_exec_id" json:"parent_exec_id"`
	Input           json.RawMessage `db:"input" json:"input"`
	Error           sql.NullString  `db:"error" json:"error"`
	Status          ExecutionStatus `db:"status" json:"status"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
}

func (q *Queries) GetExecutionByExecID(ctx context.Context, arg GetExecutionByExecIDParams) (GetExecutionByExecIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByExecID, arg.ExecID, arg.Uuid)
	var i GetExecutionByExecIDRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggeredByUuid,
	)
	return i, err
}

const getExecutionByExecIDWithNamespace = `-- name: GetExecutionByExecIDWithNamespace :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT
    el.id, el.exec_id, el.flow_id, el.parent_exec_id, el.input, el.error, el.status, el.triggered_by, el.namespace_id, el.created_at, el.updated_at,
    u.uuid AS triggered_by_uuid
FROM
    execution_log el
INNER JOIN
    users u ON el.triggered_by = u.id
INNER JOIN
    flows f ON el.flow_id = f.id
WHERE
    el.exec_id = $1
    AND f.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetExecutionByExecIDWithNamespaceParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

type GetExecutionByExecIDWithNamespaceRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	ParentExecID    sql.NullString  `db:"parent_exec_id" json:"parent_exec_id"`
	Input           json.RawMessage `db:"input" json:"input"`
	Error           sql.NullString  `db:"error" json:"error"`
	Status          ExecutionStatus `db:"status" json:"status"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
}

func (q *Queries) GetExecutionByExecIDWithNamespace(ctx context.Context, arg GetExecutionByExecIDWithNamespaceParams) (GetExecutionByExecIDWithNamespaceRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByExecIDWithNamespace, arg.ExecID, arg.Uuid)
	var i GetExecutionByExecIDWithNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggeredByUuid,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, namespace_id, created_at, updated_at FROM execution_log 
WHERE execution_log.id = $1 AND execution_log.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetExecutionByIDParams struct {
	ID   int32     `db:"id" json:"id"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetExecutionByID(ctx context.Context, arg GetExecutionByIDParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByID, arg.ID, arg.Uuid)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionsByFlow = `-- name: GetExecutionsByFlow :many
WITH user_lookup AS (
    SELECT id FROM users WHERE users.uuid = $2
), namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $3
)
SELECT el.id, el.exec_id, el.flow_id, el.parent_exec_id, el.input, el.error, el.status, el.triggered_by, el.namespace_id, el.created_at, el.updated_at FROM execution_log el
INNER JOIN flows f ON el.flow_id = f.id
WHERE f.id = $1 
  AND el.triggered_by = (SELECT id FROM user_lookup)
  AND f.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetExecutionsByFlowParams struct {
	ID     int32     `db:"id" json:"id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) GetExecutionsByFlow(ctx context.Context, arg GetExecutionsByFlowParams) ([]ExecutionLog, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByFlow, arg.ID, arg.Uuid, arg.Uuid_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionLog
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.ParentExecID,
			&i.Input,
			&i.Error,
			&i.Status,
			&i.TriggeredBy,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowFromExecID = `-- name: GetFlowFromExecID :one
WITH exec_log AS (
    SELECT flow_id FROM execution_log WHERE exec_id = $1
), namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.namespace_id, f.created_at, f.updated_at FROM flows f 
INNER JOIN exec_log el ON el.flow_id = f.id
WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetFlowFromExecIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetFlowFromExecID(ctx context.Context, arg GetFlowFromExecIDParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowFromExecID, arg.ExecID, arg.Uuid)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowFromExecIDWithNamespace = `-- name: GetFlowFromExecIDWithNamespace :one
WITH exec_log AS (
    SELECT flow_id FROM execution_log WHERE exec_id = $1
), namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.namespace_id, f.created_at, f.updated_at FROM flows f
INNER JOIN exec_log el ON el.flow_id = f.id
WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetFlowFromExecIDWithNamespaceParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetFlowFromExecIDWithNamespace(ctx context.Context, arg GetFlowFromExecIDWithNamespaceParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowFromExecIDWithNamespace, arg.ExecID, arg.Uuid)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInputForExecByUUID = `-- name: GetInputForExecByUUID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT input FROM execution_log 
WHERE execution_log.exec_id = $1 AND execution_log.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetInputForExecByUUIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetInputForExecByUUID(ctx context.Context, arg GetInputForExecByUUIDParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getInputForExecByUUID, arg.ExecID, arg.Uuid)
	var input json.RawMessage
	err := row.Scan(&input)
	return input, err
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $5
)
UPDATE execution_log SET status=$1, error=$2, updated_at=$3 
WHERE exec_id = $4 AND namespace_id = (SELECT id FROM namespace_lookup) 
RETURNING id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, namespace_id, created_at, updated_at
`

type UpdateExecutionStatusParams struct {
	Status    ExecutionStatus `db:"status" json:"status"`
	Error     sql.NullString  `db:"error" json:"error"`
	UpdatedAt time.Time       `db:"updated_at" json:"updated_at"`
	ExecID    string          `db:"exec_id" json:"exec_id"`
	Uuid      uuid.UUID       `db:"uuid" json:"uuid"`
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, updateExecutionStatus,
		arg.Status,
		arg.Error,
		arg.UpdatedAt,
		arg.ExecID,
		arg.Uuid,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
