// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flows.sql

package repo

import (
	"context"
	"database/sql"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (
    slug,
    name,
    description
) VALUES (
    $1, $2, $3
) RETURNING id, slug, name, description, created_at, updated_at
`

type CreateFlowParams struct {
	Slug        string         `db:"slug" json:"slug"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, createFlow, arg.Slug, arg.Name, arg.Description)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllFlows = `-- name: DeleteAllFlows :exec
DELETE FROM flows
`

func (q *Queries) DeleteAllFlows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFlows)
	return err
}

const getFlowBySlug = `-- name: GetFlowBySlug :one
SELECT id, slug, name, description, created_at, updated_at FROM flows where slug = $1
`

func (q *Queries) GetFlowBySlug(ctx context.Context, slug string) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowBySlug, slug)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
