// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPassword(ctx context.Context, id int32) (sql.NullString, error)
}

var _ Querier = (*Queries)(nil)
