// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password,
    login_type,
    role,
    name
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, uuid, name, username, password, login_type, role, created_at, updated_at
`

type CreateUserParams struct {
	Username  string         `db:"username" json:"username"`
	Password  sql.NullString `db:"password" json:"password"`
	LoginType UserLoginType  `db:"login_type" json:"login_type"`
	Role      UserRoleType   `db:"role" json:"role"`
	Name      string         `db:"name" json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.LoginType,
		arg.Role,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUsersWithGroups = `-- name: GetAllUsersWithGroups :many
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups FROM user_view
`

func (q *Queries) GetAllUsersWithGroups(ctx context.Context) ([]UserView, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersWithGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserView
	for rows.Next() {
		var i UserView
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.LoginType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT
    u.id AS user_id,
    u.uuid,
    u.username,
    u.password,
    array_agg(g.name) AS group_names,
    array_agg(g.description) AS group_descriptions
FROM
    users u
LEFT JOIN
    group_memberships gm ON u.id = gm.user_id
LEFT JOIN
    groups g ON gm.group_id = g.id
WHERE
    u.uuid = $1
GROUP BY
    u.id, u.uuid, u.username, u.password
`

type GetUserByUUIDRow struct {
	UserID            int32          `db:"user_id" json:"user_id"`
	Uuid              uuid.UUID      `db:"uuid" json:"uuid"`
	Username          string         `db:"username" json:"username"`
	Password          sql.NullString `db:"password" json:"password"`
	GroupNames        interface{}    `db:"group_names" json:"group_names"`
	GroupDescriptions interface{}    `db:"group_descriptions" json:"group_descriptions"`
}

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (GetUserByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, argUuid)
	var i GetUserByUUIDRow
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.Username,
		&i.Password,
		&i.GroupNames,
		&i.GroupDescriptions,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    u.id AS user_id,
    u.uuid,
    u.username,
    u.password,
    array_agg(g.name) AS group_names,
    array_agg(g.description) AS group_descriptions
FROM
    users u
LEFT JOIN
    group_memberships gm ON u.id = gm.user_id
LEFT JOIN
    groups g ON gm.group_id = g.id
WHERE
    u.username = $1
GROUP BY
    u.id, u.uuid, u.username, u.password
`

type GetUserByUsernameRow struct {
	UserID            int32          `db:"user_id" json:"user_id"`
	Uuid              uuid.UUID      `db:"uuid" json:"uuid"`
	Username          string         `db:"username" json:"username"`
	Password          sql.NullString `db:"password" json:"password"`
	GroupNames        interface{}    `db:"group_names" json:"group_names"`
	GroupDescriptions interface{}    `db:"group_descriptions" json:"group_descriptions"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.Username,
		&i.Password,
		&i.GroupNames,
		&i.GroupDescriptions,
	)
	return i, err
}

const searchUser = `-- name: SearchUser :many
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups FROM user_view WHERE lower(name) LIKE '%' || lower($1::text) || '%' OR lower(username) LIKE '%' || lower($1::text) || '%'
`

func (q *Queries) SearchUser(ctx context.Context, dollar_1 string) ([]UserView, error) {
	rows, err := q.db.QueryContext(ctx, searchUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserView
	for rows.Next() {
		var i UserView
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.LoginType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
