// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: webhooks.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createNamespaceWebhook = `-- name: CreateNamespaceWebhook :one
INSERT INTO namespace_webhooks (
    name,
    description,
    type,
    encrypted_url,
    encrypted_headers,
    content_type,
    template_body,
    template_format,
    is_active,
    namespace_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    (SELECT id FROM namespaces WHERE namespaces.uuid = $10)
)
RETURNING id, uuid, name, description, type, encrypted_url, encrypted_headers, content_type, template_body, template_format, is_active, namespace_id, created_at, updated_at
`

type CreateNamespaceWebhookParams struct {
	Name             string         `db:"name" json:"name"`
	Description      sql.NullString `db:"description" json:"description"`
	Type             string         `db:"type" json:"type"`
	EncryptedUrl     string         `db:"encrypted_url" json:"encrypted_url"`
	EncryptedHeaders sql.NullString `db:"encrypted_headers" json:"encrypted_headers"`
	ContentType      string         `db:"content_type" json:"content_type"`
	TemplateBody     string         `db:"template_body" json:"template_body"`
	TemplateFormat   string         `db:"template_format" json:"template_format"`
	IsActive         bool           `db:"is_active" json:"is_active"`
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
}

func (q *Queries) CreateNamespaceWebhook(ctx context.Context, arg CreateNamespaceWebhookParams) (NamespaceWebhook, error) {
	row := q.db.QueryRowContext(ctx, createNamespaceWebhook,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.EncryptedUrl,
		arg.EncryptedHeaders,
		arg.ContentType,
		arg.TemplateBody,
		arg.TemplateFormat,
		arg.IsActive,
		arg.Uuid,
	)
	var i NamespaceWebhook
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.EncryptedUrl,
		&i.EncryptedHeaders,
		&i.ContentType,
		&i.TemplateBody,
		&i.TemplateFormat,
		&i.IsActive,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNamespaceWebhook = `-- name: DeleteNamespaceWebhook :exec
DELETE FROM namespace_webhooks
WHERE namespace_webhooks.uuid = $1
  AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
`

type DeleteNamespaceWebhookParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) DeleteNamespaceWebhook(ctx context.Context, arg DeleteNamespaceWebhookParams) error {
	_, err := q.db.ExecContext(ctx, deleteNamespaceWebhook, arg.Uuid, arg.Uuid_2)
	return err
}

const getNamespaceWebhookByID = `-- name: GetNamespaceWebhookByID :one
SELECT w.id, w.uuid, w.name, w.description, w.type, w.encrypted_url, w.encrypted_headers, w.content_type, w.template_body, w.template_format, w.is_active, w.namespace_id, w.created_at, w.updated_at, ns.uuid AS namespace_uuid
FROM namespace_webhooks w
JOIN namespaces ns ON w.namespace_id = ns.id
WHERE w.id = $1
`

type GetNamespaceWebhookByIDRow struct {
	ID               int32          `db:"id" json:"id"`
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
	Name             string         `db:"name" json:"name"`
	Description      sql.NullString `db:"description" json:"description"`
	Type             string         `db:"type" json:"type"`
	EncryptedUrl     string         `db:"encrypted_url" json:"encrypted_url"`
	EncryptedHeaders sql.NullString `db:"encrypted_headers" json:"encrypted_headers"`
	ContentType      string         `db:"content_type" json:"content_type"`
	TemplateBody     string         `db:"template_body" json:"template_body"`
	TemplateFormat   string         `db:"template_format" json:"template_format"`
	IsActive         bool           `db:"is_active" json:"is_active"`
	NamespaceID      int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid    uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetNamespaceWebhookByID(ctx context.Context, id int32) (GetNamespaceWebhookByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceWebhookByID, id)
	var i GetNamespaceWebhookByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.EncryptedUrl,
		&i.EncryptedHeaders,
		&i.ContentType,
		&i.TemplateBody,
		&i.TemplateFormat,
		&i.IsActive,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const getNamespaceWebhookByName = `-- name: GetNamespaceWebhookByName :one
SELECT w.id, w.uuid, w.name, w.description, w.type, w.encrypted_url, w.encrypted_headers, w.content_type, w.template_body, w.template_format, w.is_active, w.namespace_id, w.created_at, w.updated_at, ns.uuid AS namespace_uuid
FROM namespace_webhooks w
JOIN namespaces ns ON w.namespace_id = ns.id
WHERE ns.uuid = $1 AND w.name = $2
`

type GetNamespaceWebhookByNameParams struct {
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
	Name string    `db:"name" json:"name"`
}

type GetNamespaceWebhookByNameRow struct {
	ID               int32          `db:"id" json:"id"`
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
	Name             string         `db:"name" json:"name"`
	Description      sql.NullString `db:"description" json:"description"`
	Type             string         `db:"type" json:"type"`
	EncryptedUrl     string         `db:"encrypted_url" json:"encrypted_url"`
	EncryptedHeaders sql.NullString `db:"encrypted_headers" json:"encrypted_headers"`
	ContentType      string         `db:"content_type" json:"content_type"`
	TemplateBody     string         `db:"template_body" json:"template_body"`
	TemplateFormat   string         `db:"template_format" json:"template_format"`
	IsActive         bool           `db:"is_active" json:"is_active"`
	NamespaceID      int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid    uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetNamespaceWebhookByName(ctx context.Context, arg GetNamespaceWebhookByNameParams) (GetNamespaceWebhookByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceWebhookByName, arg.Uuid, arg.Name)
	var i GetNamespaceWebhookByNameRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.EncryptedUrl,
		&i.EncryptedHeaders,
		&i.ContentType,
		&i.TemplateBody,
		&i.TemplateFormat,
		&i.IsActive,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const getNamespaceWebhookByUUID = `-- name: GetNamespaceWebhookByUUID :one
SELECT w.id, w.uuid, w.name, w.description, w.type, w.encrypted_url, w.encrypted_headers, w.content_type, w.template_body, w.template_format, w.is_active, w.namespace_id, w.created_at, w.updated_at, ns.uuid AS namespace_uuid
FROM namespace_webhooks w
JOIN namespaces ns ON w.namespace_id = ns.id
WHERE w.uuid = $1 AND ns.uuid = $2
`

type GetNamespaceWebhookByUUIDParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetNamespaceWebhookByUUIDRow struct {
	ID               int32          `db:"id" json:"id"`
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
	Name             string         `db:"name" json:"name"`
	Description      sql.NullString `db:"description" json:"description"`
	Type             string         `db:"type" json:"type"`
	EncryptedUrl     string         `db:"encrypted_url" json:"encrypted_url"`
	EncryptedHeaders sql.NullString `db:"encrypted_headers" json:"encrypted_headers"`
	ContentType      string         `db:"content_type" json:"content_type"`
	TemplateBody     string         `db:"template_body" json:"template_body"`
	TemplateFormat   string         `db:"template_format" json:"template_format"`
	IsActive         bool           `db:"is_active" json:"is_active"`
	NamespaceID      int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid    uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetNamespaceWebhookByUUID(ctx context.Context, arg GetNamespaceWebhookByUUIDParams) (GetNamespaceWebhookByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceWebhookByUUID, arg.Uuid, arg.Uuid_2)
	var i GetNamespaceWebhookByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.EncryptedUrl,
		&i.EncryptedHeaders,
		&i.ContentType,
		&i.TemplateBody,
		&i.TemplateFormat,
		&i.IsActive,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const listNamespaceWebhooks = `-- name: ListNamespaceWebhooks :many
SELECT w.id, w.uuid, w.name, w.description, w.type, w.encrypted_url, w.encrypted_headers, w.content_type, w.template_body, w.template_format, w.is_active, w.namespace_id, w.created_at, w.updated_at, ns.uuid AS namespace_uuid
FROM namespace_webhooks w
JOIN namespaces ns ON w.namespace_id = ns.id
WHERE ns.uuid = $1
ORDER BY w.updated_at DESC
`

type ListNamespaceWebhooksRow struct {
	ID               int32          `db:"id" json:"id"`
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
	Name             string         `db:"name" json:"name"`
	Description      sql.NullString `db:"description" json:"description"`
	Type             string         `db:"type" json:"type"`
	EncryptedUrl     string         `db:"encrypted_url" json:"encrypted_url"`
	EncryptedHeaders sql.NullString `db:"encrypted_headers" json:"encrypted_headers"`
	ContentType      string         `db:"content_type" json:"content_type"`
	TemplateBody     string         `db:"template_body" json:"template_body"`
	TemplateFormat   string         `db:"template_format" json:"template_format"`
	IsActive         bool           `db:"is_active" json:"is_active"`
	NamespaceID      int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid    uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) ListNamespaceWebhooks(ctx context.Context, argUuid uuid.UUID) ([]ListNamespaceWebhooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaceWebhooks, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNamespaceWebhooksRow
	for rows.Next() {
		var i ListNamespaceWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.EncryptedUrl,
			&i.EncryptedHeaders,
			&i.ContentType,
			&i.TemplateBody,
			&i.TemplateFormat,
			&i.IsActive,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNamespaceWebhook = `-- name: UpdateNamespaceWebhook :one
UPDATE namespace_webhooks
SET
    name = $2,
    description = $3,
    type = $4,
    encrypted_url = $5,
    encrypted_headers = $6,
    content_type = $7,
    template_body = $8,
    template_format = $9,
    is_active = $10,
    updated_at = NOW()
WHERE namespace_webhooks.uuid = $1
  AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $11)
RETURNING id, uuid, name, description, type, encrypted_url, encrypted_headers, content_type, template_body, template_format, is_active, namespace_id, created_at, updated_at
`

type UpdateNamespaceWebhookParams struct {
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
	Name             string         `db:"name" json:"name"`
	Description      sql.NullString `db:"description" json:"description"`
	Type             string         `db:"type" json:"type"`
	EncryptedUrl     string         `db:"encrypted_url" json:"encrypted_url"`
	EncryptedHeaders sql.NullString `db:"encrypted_headers" json:"encrypted_headers"`
	ContentType      string         `db:"content_type" json:"content_type"`
	TemplateBody     string         `db:"template_body" json:"template_body"`
	TemplateFormat   string         `db:"template_format" json:"template_format"`
	IsActive         bool           `db:"is_active" json:"is_active"`
	Uuid_2           uuid.UUID      `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) UpdateNamespaceWebhook(ctx context.Context, arg UpdateNamespaceWebhookParams) (NamespaceWebhook, error) {
	row := q.db.QueryRowContext(ctx, updateNamespaceWebhook,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.EncryptedUrl,
		arg.EncryptedHeaders,
		arg.ContentType,
		arg.TemplateBody,
		arg.TemplateFormat,
		arg.IsActive,
		arg.Uuid_2,
	)
	var i NamespaceWebhook
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.EncryptedUrl,
		&i.EncryptedHeaders,
		&i.ContentType,
		&i.TemplateBody,
		&i.TemplateFormat,
		&i.IsActive,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    webhook_id,
    flow_id,
    execution_id,
    event
)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, webhook_id, flow_id, execution_id, event, status, attempt_count, next_attempt_at, last_status_code, last_error_message, delivered_at, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID   int32  `db:"webhook_id" json:"webhook_id"`
	FlowID      string `db:"flow_id" json:"flow_id"`
	ExecutionID string `db:"execution_id" json:"execution_id"`
	Event       string `db:"event" json:"event"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, createWebhookDelivery,
		arg.WebhookID,
		arg.FlowID,
		arg.ExecutionID,
		arg.Event,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.WebhookID,
		&i.FlowID,
		&i.ExecutionID,
		&i.Event,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastErrorMessage,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDeliveryByUUID = `-- name: GetWebhookDeliveryByUUID :one
SELECT id, uuid, webhook_id, flow_id, execution_id, event, status, attempt_count, next_attempt_at, last_status_code, last_error_message, delivered_at, created_at, updated_at FROM webhook_deliveries
WHERE uuid = $1
`

func (q *Queries) GetWebhookDeliveryByUUID(ctx context.Context, uuid uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, getWebhookDeliveryByUUID, uuid)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.WebhookID,
		&i.FlowID,
		&i.ExecutionID,
		&i.Event,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastErrorMessage,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookDelivery = `-- name: UpdateWebhookDelivery :one
UPDATE webhook_deliveries
SET
    status = $2,
    attempt_count = $3,
    next_attempt_at = $4,
    last_status_code = $5,
    last_error_message = $6,
    delivered_at = $7,
    updated_at = NOW()
WHERE uuid = $1
RETURNING id, uuid, webhook_id, flow_id, execution_id, event, status, attempt_count, next_attempt_at, last_status_code, last_error_message, delivered_at, created_at, updated_at
`

type UpdateWebhookDeliveryParams struct {
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
	Status           string         `db:"status" json:"status"`
	AttemptCount     int32          `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt    sql.NullTime   `db:"next_attempt_at" json:"next_attempt_at"`
	LastStatusCode   sql.NullInt32  `db:"last_status_code" json:"last_status_code"`
	LastErrorMessage sql.NullString `db:"last_error_message" json:"last_error_message"`
	DeliveredAt      sql.NullTime   `db:"delivered_at" json:"delivered_at"`
}

func (q *Queries) UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, updateWebhookDelivery,
		arg.Uuid,
		arg.Status,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.LastStatusCode,
		arg.LastErrorMessage,
		arg.DeliveredAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.WebhookID,
		&i.FlowID,
		&i.ExecutionID,
		&i.Event,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastErrorMessage,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addWebhookDeliveryAttempt = `-- name: AddWebhookDeliveryAttempt :one
INSERT INTO webhook_delivery_attempts (
    delivery_id,
    attempt_number,
    status_code,
    error_message,
    duration_ms
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, delivery_id, attempt_number, status_code, error_message, duration_ms, created_at
`

type AddWebhookDeliveryAttemptParams struct {
	DeliveryID    uuid.UUID      `db:"delivery_id" json:"delivery_id"`
	AttemptNumber int32          `db:"attempt_number" json:"attempt_number"`
	StatusCode    sql.NullInt32  `db:"status_code" json:"status_code"`
	ErrorMessage  sql.NullString `db:"error_message" json:"error_message"`
	DurationMs    sql.NullInt32  `db:"duration_ms" json:"duration_ms"`
}

func (q *Queries) AddWebhookDeliveryAttempt(ctx context.Context, arg AddWebhookDeliveryAttemptParams) (WebhookDeliveryAttempt, error) {
	row := q.db.QueryRowContext(ctx, addWebhookDeliveryAttempt,
		arg.DeliveryID,
		arg.AttemptNumber,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.DurationMs,
	)
	var i WebhookDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.AttemptNumber,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}
