// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: sdk/plugin/proto/executor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutorPlugin_GetName_FullMethodName         = "/proto.ExecutorPlugin/GetName"
	ExecutorPlugin_GetSchema_FullMethodName       = "/proto.ExecutorPlugin/GetSchema"
	ExecutorPlugin_GetCapabilities_FullMethodName = "/proto.ExecutorPlugin/GetCapabilities"
	ExecutorPlugin_New_FullMethodName             = "/proto.ExecutorPlugin/New"
	ExecutorPlugin_Execute_FullMethodName         = "/proto.ExecutorPlugin/Execute"
)

// ExecutorPluginClient is the client API for ExecutorPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutorPluginClient interface {
	GetName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetNameResponse, error)
	GetSchema(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*NewResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error)
}

type executorPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorPluginClient(cc grpc.ClientConnInterface) ExecutorPluginClient {
	return &executorPluginClient{cc}
}

func (c *executorPluginClient) GetName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNameResponse)
	err := c.cc.Invoke(ctx, ExecutorPlugin_GetName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorPluginClient) GetSchema(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, ExecutorPlugin_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorPluginClient) GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ExecutorPlugin_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorPluginClient) New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*NewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewResponse)
	err := c.cc.Invoke(ctx, ExecutorPlugin_New_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorPluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutorPlugin_ServiceDesc.Streams[0], ExecutorPlugin_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutorPlugin_ExecuteClient = grpc.ServerStreamingClient[ExecuteResponse]

// ExecutorPluginServer is the server API for ExecutorPlugin service.
// All implementations must embed UnimplementedExecutorPluginServer
// for forward compatibility.
type ExecutorPluginServer interface {
	GetName(context.Context, *emptypb.Empty) (*GetNameResponse, error)
	GetSchema(context.Context, *emptypb.Empty) (*GetSchemaResponse, error)
	GetCapabilities(context.Context, *emptypb.Empty) (*GetCapabilitiesResponse, error)
	New(context.Context, *NewRequest) (*NewResponse, error)
	Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error
	mustEmbedUnimplementedExecutorPluginServer()
}

// UnimplementedExecutorPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutorPluginServer struct{}

func (UnimplementedExecutorPluginServer) GetName(context.Context, *emptypb.Empty) (*GetNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetName not implemented")
}
func (UnimplementedExecutorPluginServer) GetSchema(context.Context, *emptypb.Empty) (*GetSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedExecutorPluginServer) GetCapabilities(context.Context, *emptypb.Empty) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedExecutorPluginServer) New(context.Context, *NewRequest) (*NewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method New not implemented")
}
func (UnimplementedExecutorPluginServer) Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedExecutorPluginServer) mustEmbedUnimplementedExecutorPluginServer() {}
func (UnimplementedExecutorPluginServer) testEmbeddedByValue()                        {}

// UnsafeExecutorPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutorPluginServer will
// result in compilation errors.
type UnsafeExecutorPluginServer interface {
	mustEmbedUnimplementedExecutorPluginServer()
}

func RegisterExecutorPluginServer(s grpc.ServiceRegistrar, srv ExecutorPluginServer) {
	// If the following call panics, it indicates UnimplementedExecutorPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutorPlugin_ServiceDesc, srv)
}

func _ExecutorPlugin_GetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorPluginServer).GetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorPlugin_GetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorPluginServer).GetName(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorPlugin_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorPluginServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorPlugin_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorPluginServer).GetSchema(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorPlugin_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorPluginServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorPlugin_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorPluginServer).GetCapabilities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorPlugin_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorPluginServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorPlugin_New_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorPluginServer).New(ctx, req.(*NewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorPlugin_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExecutorPluginServer).Execute(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutorPlugin_ExecuteServer = grpc.ServerStreamingServer[ExecuteResponse]

// ExecutorPlugin_ServiceDesc is the grpc.ServiceDesc for ExecutorPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutorPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ExecutorPlugin",
	HandlerType: (*ExecutorPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetName",
			Handler:    _ExecutorPlugin_GetName_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _ExecutorPlugin_GetSchema_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _ExecutorPlugin_GetCapabilities_Handler,
		},
		{
			MethodName: "New",
			Handler:    _ExecutorPlugin_New_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _ExecutorPlugin_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdk/plugin/proto/executor.proto",
}
