// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sdk/plugin/proto/executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLine_Stream int32

const (
	LogLine_STDOUT LogLine_Stream = 0
	LogLine_STDERR LogLine_Stream = 1
)

// Enum value maps for LogLine_Stream.
var (
	LogLine_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	LogLine_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x LogLine_Stream) Enum() *LogLine_Stream {
	p := new(LogLine_Stream)
	*p = x
	return p
}

func (x LogLine_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLine_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_plugin_proto_executor_proto_enumTypes[0].Descriptor()
}

func (LogLine_Stream) Type() protoreflect.EnumType {
	return &file_sdk_plugin_proto_executor_proto_enumTypes[0]
}

func (x LogLine_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLine_Stream.Descriptor instead.
func (LogLine_Stream) EnumDescriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{5, 0}
}

type Node struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port           int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	AuthMethod     string                 `protobuf:"bytes,4,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`
	AuthKey        string                 `protobuf:"bytes,5,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	ConnectionType string                 `protobuf:"bytes,6,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	OsFamily       string                 `protobuf:"bytes,7,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Node) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Node) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Node) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *Node) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *Node) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

func (x *Node) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

type ExecutionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithConfig    []byte                 `protobuf:"bytes,1,opt,name=with_config,json=withConfig,proto3" json:"with_config,omitempty"`
	Inputs        map[string]string      `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserUuid      string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	NamespaceName string                 `protobuf:"bytes,4,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiBaseUrl    string                 `protobuf:"bytes,6,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionContext) GetWithConfig() []byte {
	if x != nil {
		return x.WithConfig
	}
	return nil
}

func (x *ExecutionContext) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecutionContext) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *ExecutionContext) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *ExecutionContext) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ExecutionContext) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

func (x *ExecutionContext) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Node          *Node                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	ExecId        string                 `protobuf:"bytes,3,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRequest) Reset() {
	*x = NewRequest{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRequest) ProtoMessage() {}

func (x *NewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRequest.ProtoReflect.Descriptor instead.
func (*NewRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{2}
}

func (x *NewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NewRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type NewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ArtifactsDir  string                 `protobuf:"bytes,2,opt,name=artifacts_dir,json=artifactsDir,proto3" json:"artifacts_dir,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewResponse) Reset() {
	*x = NewResponse{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewResponse) ProtoMessage() {}

func (x *NewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewResponse.ProtoReflect.Descriptor instead.
func (*NewResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{3}
}

func (x *NewResponse) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *NewResponse) GetArtifactsDir() string {
	if x != nil {
		return x.ArtifactsDir
	}
	return ""
}

func (x *NewResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecCtx       *ExecutionContext      `protobuf:"bytes,2,opt,name=exec_ctx,json=execCtx,proto3" json:"exec_ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *ExecuteRequest) GetExecCtx() *ExecutionContext {
	if x != nil {
		return x.ExecCtx
	}
	return nil
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        LogLine_Stream         `protobuf:"varint,1,opt,name=stream,proto3,enum=proto.LogLine_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{5}
}

func (x *LogLine) GetStream() LogLine_Stream {
	if x != nil {
		return x.Stream
	}
	return LogLine_STDOUT
}

func (x *LogLine) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       map[string]string      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Globals       map[string]string      `protobuf:"bytes,3,rep,name=globals,proto3" json:"globals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{6}
}

func (x *Result) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Result) GetGlobals() map[string]string {
	if x != nil {
		return x.Globals
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteResponse_Log
	//	*ExecuteResponse_Result
	Payload       isExecuteResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetPayload() isExecuteResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *ExecuteResponse) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isExecuteResponse_Payload interface {
	isExecuteResponse_Payload()
}

type ExecuteResponse_Log struct {
	Log *LogLine `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type ExecuteResponse_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*ExecuteResponse_Log) isExecuteResponse_Payload() {}

func (*ExecuteResponse_Result) isExecuteResponse_Payload() {}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaJson    []byte                 `protobuf:"bytes,1,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{8}
}

func (x *GetSchemaResponse) GetSchemaJson() []byte {
	if x != nil {
		return x.SchemaJson
	}
	return nil
}

type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  uint64                 `protobuf:"varint,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{9}
}

func (x *GetCapabilitiesResponse) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

type GetNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNameResponse) Reset() {
	*x = GetNameResponse{}
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNameResponse) ProtoMessage() {}

func (x *GetNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNameResponse.ProtoReflect.Descriptor instead.
func (*GetNameResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_executor_proto_rawDescGZIP(), []int{10}
}

func (x *GetNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_sdk_plugin_proto_executor_proto protoreflect.FileDescriptor

const file_sdk_plugin_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x1fsdk/plugin/proto/executor.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd4\x01\n" +
	"\x04Node\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1f\n" +
	"\vauth_method\x18\x04 \x01(\tR\n" +
	"authMethod\x12\x19\n" +
	"\bauth_key\x18\x05 \x01(\tR\aauthKey\x12'\n" +
	"\x0fconnection_type\x18\x06 \x01(\tR\x0econnectionType\x12\x1b\n" +
	"\tos_family\x18\a \x01(\tR\bosFamily\"\xcd\x02\n" +
	"\x10ExecutionContext\x12\x1f\n" +
	"\vwith_config\x18\x01 \x01(\fR\n" +
	"withConfig\x12;\n" +
	"\x06inputs\x18\x02 \x03(\v2#.proto.ExecutionContext.InputsEntryR\x06inputs\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12%\n" +
	"\x0enamespace_name\x18\x04 \x01(\tR\rnamespaceName\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12 \n" +
	"\fapi_base_url\x18\x06 \x01(\tR\n" +
	"apiBaseUrl\x12!\n" +
	"\x05nodes\x18\a \x03(\v2\v.proto.NodeR\x05nodes\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\n" +
	"NewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x04node\x18\x02 \x01(\v2\v.proto.NodeR\x04node\x12\x17\n" +
	"\aexec_id\x18\x03 \x01(\tR\x06execId\"i\n" +
	"\vNewResponse\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12#\n" +
	"\rartifacts_dir\x18\x02 \x01(\tR\fartifactsDir\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"e\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x122\n" +
	"\bexec_ctx\x18\x02 \x01(\v2\x17.proto.ExecutionContextR\aexecCtx\"n\n" +
	"\aLogLine\x12-\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x15.proto.LogLine.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"\x82\x02\n" +
	"\x06Result\x124\n" +
	"\aoutputs\x18\x01 \x03(\v2\x1a.proto.Result.OutputsEntryR\aoutputs\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x124\n" +
	"\aglobals\x18\x03 \x03(\v2\x1a.proto.Result.GlobalsEntryR\aglobals\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fGlobalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x0fExecuteResponse\x12\"\n" +
	"\x03log\x18\x01 \x01(\v2\x0e.proto.LogLineH\x00R\x03log\x12'\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultH\x00R\x06resultB\t\n" +
	"\apayload\"4\n" +
	"\x11GetSchemaResponse\x12\x1f\n" +
	"\vschema_json\x18\x01 \x01(\fR\n" +
	"schemaJson\"=\n" +
	"\x17GetCapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x01(\x04R\fcapabilities\"%\n" +
	"\x0fGetNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xbf\x02\n" +
	"\x0eExecutorPlugin\x129\n" +
	"\aGetName\x12\x16.google.protobuf.Empty\x1a\x16.proto.GetNameResponse\x12=\n" +
	"\tGetSchema\x12\x16.google.protobuf.Empty\x1a\x18.proto.GetSchemaResponse\x12I\n" +
	"\x0fGetCapabilities\x12\x16.google.protobuf.Empty\x1a\x1e.proto.GetCapabilitiesResponse\x12,\n" +
	"\x03New\x12\x11.proto.NewRequest\x1a\x12.proto.NewResponse\x12:\n" +
	"\aExecute\x12\x15.proto.ExecuteRequest\x1a\x16.proto.ExecuteResponse0\x01B1Z/github.com/cvhariharan/flowctl/sdk/plugin/protob\x06proto3"

var (
	file_sdk_plugin_proto_executor_proto_rawDescOnce sync.Once
	file_sdk_plugin_proto_executor_proto_rawDescData []byte
)

func file_sdk_plugin_proto_executor_proto_rawDescGZIP() []byte {
	file_sdk_plugin_proto_executor_proto_rawDescOnce.Do(func() {
		file_sdk_plugin_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_plugin_proto_executor_proto_rawDesc), len(file_sdk_plugin_proto_executor_proto_rawDesc)))
	})
	return file_sdk_plugin_proto_executor_proto_rawDescData
}

var file_sdk_plugin_proto_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_plugin_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sdk_plugin_proto_executor_proto_goTypes = []any{
	(LogLine_Stream)(0),             // 0: proto.LogLine.Stream
	(*Node)(nil),                    // 1: proto.Node
	(*ExecutionContext)(nil),        // 2: proto.ExecutionContext
	(*NewRequest)(nil),              // 3: proto.NewRequest
	(*NewResponse)(nil),             // 4: proto.NewResponse
	(*ExecuteRequest)(nil),          // 5: proto.ExecuteRequest
	(*LogLine)(nil),                 // 6: proto.LogLine
	(*Result)(nil),                  // 7: proto.Result
	(*ExecuteResponse)(nil),         // 8: proto.ExecuteResponse
	(*GetSchemaResponse)(nil),       // 9: proto.GetSchemaResponse
	(*GetCapabilitiesResponse)(nil), // 10: proto.GetCapabilitiesResponse
	(*GetNameResponse)(nil),         // 11: proto.GetNameResponse
	nil,                             // 12: proto.ExecutionContext.InputsEntry
	nil,                             // 13: proto.Result.OutputsEntry
	nil,                             // 14: proto.Result.GlobalsEntry
	(*emptypb.Empty)(nil),           // 15: google.protobuf.Empty
}
var file_sdk_plugin_proto_executor_proto_depIdxs = []int32{
	12, // 0: proto.ExecutionContext.inputs:type_name -> proto.ExecutionContext.InputsEntry
	1,  // 1: proto.ExecutionContext.nodes:type_name -> proto.Node
	1,  // 2: proto.NewRequest.node:type_name -> proto.Node
	2,  // 3: proto.ExecuteRequest.exec_ctx:type_name -> proto.ExecutionContext
	0,  // 4: proto.LogLine.stream:type_name -> proto.LogLine.Stream
	13, // 5: proto.Result.outputs:type_name -> proto.Result.OutputsEntry
	14, // 6: proto.Result.globals:type_name -> proto.Result.GlobalsEntry
	6,  // 7: proto.ExecuteResponse.log:type_name -> proto.LogLine
	7,  // 8: proto.ExecuteResponse.result:type_name -> proto.Result
	15, // 9: proto.ExecutorPlugin.GetName:input_type -> google.protobuf.Empty
	15, // 10: proto.ExecutorPlugin.GetSchema:input_type -> google.protobuf.Empty
	15, // 11: proto.ExecutorPlugin.GetCapabilities:input_type -> google.protobuf.Empty
	3,  // 12: proto.ExecutorPlugin.New:input_type -> proto.NewRequest
	5,  // 13: proto.ExecutorPlugin.Execute:input_type -> proto.ExecuteRequest
	11, // 14: proto.ExecutorPlugin.GetName:output_type -> proto.GetNameResponse
	9,  // 15: proto.ExecutorPlugin.GetSchema:output_type -> proto.GetSchemaResponse
	10, // 16: proto.ExecutorPlugin.GetCapabilities:output_type -> proto.GetCapabilitiesResponse
	4,  // 17: proto.ExecutorPlugin.New:output_type -> proto.NewResponse
	8,  // 18: proto.ExecutorPlugin.Execute:output_type -> proto.ExecuteResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_sdk_plugin_proto_executor_proto_init() }
func file_sdk_plugin_proto_executor_proto_init() {
	if File_sdk_plugin_proto_executor_proto != nil {
		return
	}
	file_sdk_plugin_proto_executor_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecuteResponse_Log)(nil),
		(*ExecuteResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_plugin_proto_executor_proto_rawDesc), len(file_sdk_plugin_proto_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_plugin_proto_executor_proto_goTypes,
		DependencyIndexes: file_sdk_plugin_proto_executor_proto_depIdxs,
		EnumInfos:         file_sdk_plugin_proto_executor_proto_enumTypes,
		MessageInfos:      file_sdk_plugin_proto_executor_proto_msgTypes,
	}.Build()
	File_sdk_plugin_proto_executor_proto = out.File
	file_sdk_plugin_proto_executor_proto_goTypes = nil
	file_sdk_plugin_proto_executor_proto_depIdxs = nil
}
